name: Unit Tests

on:
  push:
    branches:
      - root  # adjust this based on your branch name

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./  # Set the working directory as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    #- name: Install dependencies
    #  run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s collections -p "*.py"
